import { ToastContainer } from "react-toastify";
import { ProvideContext } from "@/app/UseAuth";
import { Raleway } from "next/font/google";
import UserLayout from "@/app/userlayout";
import "./globals.css";

const ralewaySans = Raleway({
  variable: "--font-raleway-sans",
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Paisa Kidhar Gaya?",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${ralewaySans.variable} antialiased`}>
        <ProvideContext>
          <UserLayout>{children}</UserLayout>
          <ToastContainer autoClose={1500} hideProgressBar />
        </ProvideContext>
      </body>
    </html>
  );
}
